trigger:
- none

pool: 'TestAgentPool'

steps:
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifest'
    backendType: 'azurerm'
    backendServiceArm: '33 Azure DevOps Provision AKS cluster 01'
    backendAzureRmSubscriptionId: 'c88c8f23-28fa-446c-9737-a0a749bb194f'
    backendAzureRmResourceGroupName: 'aks-resources-rg'
    backendAzureRmStorageAccountName: 'storageaccountshola'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'aks-base.tfstate'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifest'
    environmentServiceName: '33 Azure DevOps Provision AKS cluster 01'
    allowTelemetryCollection: false
