
trigger:
- none

pool: 'TestAgentPool'

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
    allowTelemetryCollection: false